---
title: "Portfolio"
---

Hi there this is my portfolio page!

Here is my resume.

+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   | Zazni Vlijter                                                                                                                                                                                                                                                                                                                                                                                      |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | Strategic Communications                                                                                                                                                                                                                                                                                                                                                                           |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   | 400 15^th^ St South, Arlington, VA                                                                                                                                                                                                                                                                                                                                                                 |   | 646-469-4755                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | # OBJECTIVE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   | Upcoming graduate from The George Washington University looking to exercise and master skills within the public relations and strategic communications field. Zazni Vlijter has over a year worth of valuable strategic communications experience in which she has mastered common public relations software, memo writing, research and building client relationships through thought leadership. |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   | ## EDUCATION ---                                                                                                                                                                                                                                                                                                                                                                                   |   | # EXPERIENCE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   | **Bachelor of Arts in English \| May 2023 \| The George Washington University**                                                                                                                                                                                                                                                                                                                    |   | **Strategic Communications Intern \| Narrative Strategies \| January 2022 - Present**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | **High School Diploma\| June 2019 \| Special Music School High School**                                                                                                                                                                                                                                                                                                                            |   | Drafted strategic memos, op-eds, letters to the editors, research press lists, client call notes and regular deliverables sent directly to clients. Created an influencer memo to identify potential branding and client opportunities. Drafted and finalized research sent firm wide regarding the future of strategic communications in the rise of AI technology. Made key connections with clients in person and on regular management calls, leading to regular client assignments and deliverables. Used common strategic communications platforms to execute high level and in depth analysis on reach, target audience and communications reception. |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | **Communications Team Lead \| International Institute of Economic Policy at The George Washington University \| September 2022 - January 2023**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | Drafted and finalized event promotion emails. Drafted social content for Facebook, Twitter, and LinkedIn. Led communication team through task delegation, editing, and regular team meetings. Crafted digital content and designs that were promoted through social media and public posters.                                                                                                                                                                                                                                                                                                                                                                |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | **Content Writer \| The Know \| May 2021 -- April 2022**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | Analyzed, organized, and categorized policy stances for political candidates through efficient excel sheet to be published on the website. Executed content writing for the website including breaking down policy stances and editing co-workers writing. Worked with Chief Executive Officer to brainstorm expansion of audience and reach of The Know to different social                                                                                                                                                                                                                                                                                 |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | media platforms. Used excel to organize data and writing.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | **Public Relations Intern \| Valentina Kozlova Dance Conservatory of New York \| September 2017 -- December 2017**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | Drafted and created social content for the company Facebook and Instagram page. Filed and categorized student and applicant data and information.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   | ## KEY SKILLS ---                                                                                                                                                                                                                                                                                                                                                                                  |   | # COMMUNICATION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   | Writing                                                                                                                                                                                                                                                                                                                                                                                            |   | **Firm Wide Presentation on Artificial Intelligence in Public Relations \| Narrative Strategies \| March 2023**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | Research                                                                                                                                                                                                                                                                                                                                                                                           |   | First intern to give a firm wide presentation on the implications of Artificial Intelligence within the public relations field and provided next steps for the firm.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | Social media                                                                                                                                                                                                                                                                                                                                                                                       |   | **Started a Firm Wide Influencer Tracker \| Narrative Strategies \| August 2022**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | Thought leadership                                                                                                                                                                                                                                                                                                                                                                                 |   | Created a firm and client wide influencer tracker to identify potential marketing and social media advertisement opportunities.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | Microsoft Suites                                                                                                                                                                                                                                                                                                                                                                                   |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | Google Suites                                                                                                                                                                                                                                                                                                                                                                                      |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | Hootsuite                                                                                                                                                                                                                                                                                                                                                                                          |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | MailChimp                                                                                                                                                                                                                                                                                                                                                                                          |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | Meltwater                                                                                                                                                                                                                                                                                                                                                                                          |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | Digimind                                                                                                                                                                                                                                                                                                                                                                                           |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | GitHub Coding Software                                                                                                                                                                                                                                                                                                                                                                             |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   | R Studios Coding Software                                                                                                                                                                                                                                                                                                                                                                          |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | # AWARDS AND LEADERSHIP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | **Executive Vice President \| Alpha Pi Chapter of Alpha Delta Pi \| November 2020 -- November 2021**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | **Recruitment Analyst \| Alpha Pi Chapter of Alpha Delta Pi \| November 2021-- November 2022**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | **Presidential Scholarship Recipient \| Columbian College of Arts and Sciences at The George Washington University**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | **Dean's List Recipient \| Columbian College of Arts and Sciences at The George Washington University**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   | **Dean's List Recipient \| Columbian College of Arts and Sciences at The George Washington University**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
|   |                                                                                                                                                                                                                                                                                                                                                                                                    |   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   |   |   |   |   |
+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+---+---+---+
